version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 845716118592.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t photo-editor .
      - docker tag photo-editor:latest 845716118592.dkr.ecr.us-east-1.amazonaws.com/photo-editor:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 845716118592.dkr.ecr.us-east-1.amazonaws.com/photo-editor:latest
      - printf '[{"name":"photo-editor","imageUri":"%s"}]' 845716118592.dkr.ecr.us-east-1.amazonaws.com/photo-editor:latest  > imagedefinitions.json

artifacts:
    files: imagedefinitions.json
